# Generated by Django 4.2.3 on 2023-10-24 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=50)),
                ('descricao_modelo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_roupa', models.CharField(max_length=50)),
                ('descricao_roupa', models.CharField(max_length=250)),
                ('composicao_roupa', models.CharField(max_length=100)),
                ('imagem_roupa', models.ImageField(upload_to='uploads/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roupas', to='site_catalogo.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roupas', to='site_catalogo.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtida_roupa', models.IntegerField()),
                ('comentario_roupa', models.TextField()),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roupa', to='site_catalogo.roupa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
