# Generated by Django 4.2.3 on 2023-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='imagem_roupa',
            field=models.ImageField(upload_to='teste/'),
        ),
    ]
