# Generated by Django 4.2.3 on 2023-10-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0002_alter_roupa_imagem_roupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='imagem_roupa',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
