# Generated by Django 4.2.5 on 2023-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0003_rename_texto_faleconosco_mensagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=255, unique=True)),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
