# Generated by Django 4.2.5 on 2023-11-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0004_roupa_liked_by_roupa_likes_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='liked_by',
        ),
    ]
