<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-11-06 21:50
=======
# Generated by Django 4.2.3 on 2023-11-06 21:54
>>>>>>> 734d1aa899f7c92e833b20ddd3fd6683f7cb8783

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_catalogo', '0007_roupa_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='site_catalogo.roupa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userroupa',
            name='roupa',
        ),
        migrations.RemoveField(
            model_name='userroupa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
        migrations.DeleteModel(
            name='UserRoupa',
        ),
    ]
