# Generated by Django 4.2.3 on 2023-11-29 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_catalogo', '0008_comentario_remove_userroupa_roupa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_produto', models.CharField(max_length=50)),
                ('descricao_produto', models.CharField(max_length=250)),
                ('composicao_produto', models.CharField(max_length=100)),
                ('imagem_produto', models.ImageField(upload_to='uploads/')),
                ('numero_comentarios', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_catalogo.ano')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_catalogo.colecao')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='produtos_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='roupa',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.DeleteModel(
            name='Roupa',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_catalogo.tipo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='site_catalogo.produto'),
        ),
    ]
