# Generated by Django 4.2.3 on 2023-11-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0009_ano_colecao_produto_tipo_remove_roupa_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='site_catalogo.produto'),
        ),
    ]
