# Generated by Django 4.2.3 on 2023-11-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0010_alter_comentario_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='produto',
            new_name='product',
        ),
    ]
