# Generated by Django 4.2.3 on 2023-11-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_catalogo', '0011_rename_produto_comentario_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
