# Generated by Django 4.2.7 on 2023-12-04 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_card', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('path', models.TextField()),
                ('primeiro_texto', models.TextField()),
                ('segundo_texto', models.TextField()),
                ('alunos', models.IntegerField()),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
