# Generated by Django 4.2.7 on 2023-12-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='alunos',
        ),
    ]
